let a="hello ";
console.log(a);
alert(a);
document.write(a);
let b="owu ";
console.log(b);
alert(b);
document.write(b);
let c="com ";
console.log(c);
alert(c);
document.write(c);
let d="ua ";
console.log(d);
alert(d);
document.write(d);
let e= 1 ;
console.log(e);
alert(e);
document.write(e + " ");
let f= 10 ;
console.log(f);
alert(f);
document.write(f + " ");
let g= -999 ;
console.log(g);
alert(g);
document.write(g + " ");
let h= 123 ;
console.log(h);
alert(h);
document.write(h + " ");
let i= 3.14 ;
console.log(i);
alert(i);
document.write(i + " ");
let j= 2.7 ;
console.log(j);
alert(j);
document.write(j + " ");
let k= 16 ;
console.log(k);
alert(k);
document.write(k + " ");
let m= true ;
console.log(m);
alert(m);
document.write(m + " ");
let n= false ;
console.log(n);
alert(n);
document.write(n + " ");

let lastName = "Ozerova";
let firstName = "Nataliia";
let middleName = "Romanivna";
let person = lastName + " " + firstName + " " + middleName;
console.log(person);

console.log(typeof 100);
console.log(typeof '100');
console.log(typeof true);

let name = prompt('Your name?');
console.log(name);
let middlename = prompt('Your middlename?');
console.log(middlename);
let age = + prompt('Your age?');
console.log(age);
